export component MainWindow inherits Window {
    width: 240px;
    height: 400px;
    title: "Test";
    background: #0F0F0F;
    default-font-family: "Noto Sans";
    default-font-size: 12px;

    magenta := Rectangle {
        x: 0px;
        y: parent.height - self.height;
        height: 20px;
        width: parent.width * abs(sin(360deg * animation-tick() / 3s));
        background: #FF00FF;
    }
}
