import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import "dist/Silkscreen-Regular.ttf";
import "dist/Silkscreen-Bold.ttf";

export component MainWindow inherits Window {
    width: 400px;
    height: 240px;
    background: blue;
    default-font-family: "Silkscreen";
    default-font-size: 20px;

    VerticalBox {
        Text {
            text: "cagou nas calças?";
            font-size: 30px;
            color: white;
        }

        Button {
            text: "sim";
            height: 30px;
        }

        Button {
            text: "com certeza";
            height: 30px;
        }
    }
}
